name: colcon build/test

on:
  workflow_dispatch:


concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-22.04
    container:
      image: ardupilot/ardupilot-dev-ros:latest
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
    steps:
      # git checkout the PR
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: src/ardupilot
      # Put ccache into github cache for faster build
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
      - name: ccache cache files
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-  # restore ccache from either previous build on this branch or on master
      - name: setup ccache
        run: |
          . src/ardupilot/.github/workflows/ccache.env
      # https://ardupilot.org/dev/docs/ros2.html#installation-ubuntu
      - name: Pull in repos with vcs
        run: |
          cd src
          wget --progress=dot:giga https://raw.githubusercontent.com/ArduPilot/ardupilot/master/Tools/ros2/ros2.repos
          vcs import --recursive --debug --shallow --skip-existing < ros2.repos
      - name: Install rosdep dependencies
        shell: 'bash'
        run: |
          apt update
          rosdep update
          python3 -m pip install flake8
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src --default-yes
      - name: Install MAVProxy
        run: |
          # Install this specific version just to prevent rolling updates.
          # See the latest available at https://pypi.org/project/MAVProxy
          python3 -m pip install MAVProxy==1.8.71
      - name: Install local pymavlink
        working-directory: ./src/ardupilot/modules/mavlink/pymavlink
        run: |
          python3 -m pip install . --upgrade --user
      # install Micro-XRCE-DDS-Gen from source until image is updated
      - name: install Micro-XRCE-DDS-Gen from source
        run: |
          cd /tmp
          git clone --depth 1 --recurse-submodules --branch v4.7.0 https://github.com/ardupilot/Micro-XRCE-DDS-Gen.git
          cd Micro-XRCE-DDS-Gen
          ./gradlew assemble
      - name: Build with colcon
        shell: 'bash'
        run: |
          source /opt/ros/humble/setup.bash
          PATH="/tmp/Micro-XRCE-DDS-Gen/scripts:$PATH"
          colcon build --packages-up-to ardupilot_dds_tests --cmake-args -DBUILD_TESTING=ON
      - name: Test with colcon
        shell: 'bash'
        run: |
          source install/setup.bash
          colcon test --python-testing "pytest" --pytest-args " --verbose" " --stepwise" --executor sequential --parallel-workers 0 --base-paths src/ardupilot --event-handlers=console_cohesion+
      - name: Report colcon test results
        run: |
          colcon test-result --all --verbose
