name: QURT Build

on:
  workflow_dispatch:


concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'ArduPilot/ardupilot'
    runs-on: 'ardupilot-qurt'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build QURT
        run: |
          ./waf configure --board QURT
          ./waf copter
          ./waf plane
          ./waf rover
          cp -a build/QURT/bin/arducopter build/QURT/ArduPilot.so
          cp -a build/QURT/bin/arducopter build/QURT/ArduPilot_Copter.so
          cp -a build/QURT/bin/arduplane build/QURT/ArduPilot_Plane.so
          cp -a build/QURT/bin/ardurover build/QURT/ArduPilot_Rover.so
          libraries/AP_HAL_QURT/packaging/make_package.sh ArduCopter arducopter
          libraries/AP_HAL_QURT/packaging/make_package.sh ArduPlane arduplane
          libraries/AP_HAL_QURT/packaging/make_package.sh Rover ardurover

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: qurt-binaries
          path: |
            build/QURT/ardupilot
            build/QURT/ArduPilot_Copter.so
            build/QURT/ArduPilot_Plane.so
            build/QURT/ArduPilot_Rover.so
            build/QURT/ArduPilot.so
            libraries/AP_HAL_QURT/packaging/*.deb
          retention-days: 7
