name: test dds

on:
  workflow_dispatch:


concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ardupilot/ardupilot-dev-ros:latest
      options: --user 1001
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        config: [
            sitl,
            stm32h7
        ]
    steps:
      # git checkout the PR
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      # Put ccache into github cache for faster build
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
      - name: ccache cache files
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{ matrix.config }}-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-${{ matrix.config }}-  # restore ccache from either previous build on this branch or on master
      - name: setup ccache
        run: |
          . .github/workflows/ccache.env
      # install Micro-XRCE-DDS-Gen from source until image is updated
      - name: install Micro-XRCE-DDS-Gen from source
        run: |
          cd /tmp
          git clone --recurse-submodules https://github.com/ardupilot/Micro-XRCE-DDS-Gen.git
          cd Micro-XRCE-DDS-Gen
          ./gradlew assemble
      - name: test ${{matrix.config}}
        env:
          CI_BUILD_TARGET: dds-${{matrix.config}}
        shell: 'script -q -e -c "bash {0}"'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/github/home/.local/bin:$PATH"
          PATH="/tmp/Micro-XRCE-DDS-Gen/scripts:$PATH"
          which microxrceddsgen
          Tools/scripts/build_ci.sh

      - name: Archive buildlog artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
           name: fail-${{matrix.config}}
           path: /tmp/buildlogs
           retention-days: 14
